language: objective-c
osx_image: xcode10
before_script:
    - bundle install
    - brew outdated carthage || brew upgrade carthage
script:
    - xcodebuild -project Valet.xcodeproj -scheme "Valet iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.0,name=iPhone X" -configuration Debug -PBXBuildsContinueAfterErrors=0 build test
    - xcodebuild -project Valet.xcodeproj -scheme "Valet tvOS" -sdk appletvsimulator12.0 -destination "platform=tvOS Simulator,name=Apple TV" -configuration Debug -PBXBuildsContinueAfterErrors=0 build test
    - xcodebuild -project Valet.xcodeproj -scheme "Valet Mac" -sdk macosx10.14 -configuration Debug -destination "platform=OS X" -PBXBuildsContinueAfterErrors=0 build test
    - xcodebuild -project Valet.xcodeproj -scheme "Valet watchOS" -sdk watchos5.0 -configuration Debug -PBXBuildsContinueAfterErrors=0 build
    - bundle exec pod lib lint --verbose --fail-fast
    - carthage build --verbose --no-skip-current
